# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d91d46cd03de9a5ee3783fbec0088905de4289780a2cec5c2b0d256a313348d846dd82a633371d49f4adcb6dffca00bdf1a641601f9aa00ab6a394a5b6a04b63

test:
  secret_key_base: e2d80dda62e0e69a18e5f26367f3d9b7ee1e8d012e053d4320a1db5e69db6f6915f9653b846989ad561fdf1222dfb90d724ede8b8620e23af6b590a708c39aa7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
